### ISSUE TITLE
svelteDemo: a11y broken with radio button options 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroSvelteDemo#18]
## Describe the bug

When tabbing through the Svelte app, the YES/NO options are not accessible. 

## To Reproduce

1. Clone repo
2. npm i / npm run dev
3. Open demo page in browser
4. Start with `name` and tab through the UI
5. You are unable to tab to the yes/no options 

Looking at the inspector, notice that both radio buttons are set to `tabindex="-1"`

## Expected behavior

User has the ability to tab to yes/no radio buttons to toggle UI. This is NOT an issue with the React app, so the root cause does not appear to be the auro-radio element. Although... Svelte may be exposing an interesting issue. 

#### Svelete
<img width="1191" alt="Screen Shot 2021-07-26 at 10 14 02 AM" src="https://user-images.githubusercontent.com/181089/127013958-46e41373-42dd-4e79-98eb-d149973da616.png">

#### React
<img width="1227" alt="Screen Shot 2021-07-26 at 10 16 55 AM" src="https://user-images.githubusercontent.com/181089/127014200-f33db248-0a4d-41d7-a105-9864738d796a.png">

**Comment by geoffrich** [comment]
Looks like the demo is on v1.3.2 of auro-radio, and the latest is 1.5. This may be fixed by https://github.com/AlaskaAirlines/auro-radio/pull/38.

**Comment by blackfalcon** [comment]
@geoffrich updating locally worked. Submitting patch soon.
